### ISSUE TITLE
Starting Path not working

### ISSUE THREAD

**Issue by aaklaus** [ryojiosawa/cinnamon#8]
After upgrading to the newest version, tests all run very quickly and pass.  Selenium screenshots and screencast all show test just sitting on the Test Console Cinnamon page in Salesforce.  We specify a different StartingPath in the test class, and it doesn't appear like Selenium is navigating to that page.  Running tests that have previously failed now all pass, but they don't actually go through the tests.

**Comment by ryojiosawa** [comment]
@aaklaus - can you pls paste your test code here?

**Comment by aaklaus** [comment]
//public class covtest_aboutme {}
public with sharing class covtest_aboutme extends cinnamon.BaseTest{

```
//public selenium1.Defaultselenium selenium;

//public override void setup(cinnamon.CN_Context context) {
//  Account acc = new Account();
//  acc.name = 'Account' + System.currentTimeMillis();
//  insert acc;
//  context.put('accId', acc.Id);
//}

public override String getStartingPath(cinnamon.CN_Context context) {
    return '/apex/covtest_navigator';
}

public override void test(cinnamon.CN_Context context) {

    String testData = 'Testing 123';
    Id cid = cov_user_utility.self.getCId();
    User uid = cov_user_utility.self.getU();

    covtest_navigator_po n = (covtest_navigator_po) context.getPageObject(covtest_navigator_po.class);
    covtest_profilepanel_dash_po d = (covtest_profilepanel_dash_po) context.getPageObject(covtest_profilepanel_dash_po.class);
    covtest_profile_profileinfo_po pp = (covtest_profile_profileinfo_po) context.getPageObject(covtest_profile_profileinfo_po.class);

    n.goDashboard();
    n.clickEmployeeLogin();

    d.clickAboutMeLink();
    pp.enterAboutMeText(TestData);
    pp.clickSaveThisInfoButton();
    pp.wait();

    List<User> user = [
        SELECT AboutMe
            FROM User
            WHERE Id = :uid.Id
        ];

    //System.debug('vouchees: ' + vouchees);

    cinnamon.Assert.assert('Test data did not match',testData==user[0].AboutMe);
    //System.assertEquals(1,vouchees.size());

    //cinnamon.Assert.assertEquals('User field not matched',testData,user[0].AboutMe);
    //System.assertEquals(lastName,vouchees[0].npe4__RelatedContact__r.LastName);
    //System.assertEquals(email,vouchees[0].npe4__RelatedContact__r.Email); 

    //String url = selenium.getLocation();
    //System.assert(url.contains('cov_vouchees'));

}

//public override void tearDown(cinnamon.CN_Context context) {
//  List<ID> Ids = new List<ID>();
//  Ids.add((String) context.get('accId'));
//  Database.delete(Ids);
//}
```

}

**Comment by ryojiosawa** [comment]
Can you change `cinnamon.CN_Context` to `cinnamon.Context` and try it again?

**Comment by aaklaus** [comment]
That worked.  Is there a way for us to find out about these kinds of changes in the updates?

On May 5, 2014, at 2:07 PM, Ryo Osawa notifications@github.com wrote:

Can you change cinnamon.CN_Context to cinnamon.Context and try it again?

**Comment by ryojiosawa** [comment]
Great.  We recently introduced Context class and made CN_Context class backward compatible for the time being as some users are still using this class.  I believe we introduced a bug when making this change.  We'll look into it further but since CN_Context class will be deprecated and eventually removed from our package, please use Context class for going forward.

As for providing updates on the changes included in the new package, we recently added release notes page below.   We plan to update this doc to include any major changes in the upcoming package version going forward.  Also, we'll update our external site when we create a new package with all the new changes as well.  This should provide more visibility into what changes are included in the new package version.  That said, if you run into issues or have questions with the new package, don't hesitant to contact us via Github Issues.

https://github.com/ryojiosawa/cinnamon/blob/master/RELEASENOTES.md

@yudiatsfdc, @nadeemg
